### PR TITLE
Bump to 0.1.5 PEDS-326

### PR DESCRIPTION
**Pull request by bobaekang**
Ticket: [PEDS-326](https://pcdc.atlassian.net/browse/PEDS-326)

This PR updates dependencies--no breaking changes only. The PR also updates `@pcdc/guppy` to version 0.1.5.

### CODE REVIEW

**Comment by bobaekang** [comment]
@grugna  I noticed from the `package-lock.json` diff that you may be using `npm` v7, which generates the lockfile in a different format. Do you want us all to use `npm` v7 for development from this point on?

**Comment by grugna** [comment]
yes, let's use 7. Thank you for pointing that out, I wan't thinking about that.

**Comment by bobaekang** [comment]
@grugna Thanks for the response.

Just to be sure, are the infrastructure set up to use v7 as well? Like, building images for testing, etc. Note that `npm` v7 only ships by default with Node v15. If the images we rely on are based on using Node 14 or lower, we may have to consider that.  

The documentation suggests that `"lockfileVersion": 2`, which I believe is what currently what `npm` v7 generates on `npm install`, is compatible with `npm` v6: https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion. I'm not entirely sure of the implications tho.

**Comment by bobaekang** [comment]
Based on our discussion, we'll stick to `"lockfileVersion": 2` for v0.1.5. We'll certainly investigate migrating to `npm` v7 for future releases. Refer to [PEDS-339](https://pcdc.atlassian.net/browse/PEDS-339).

**Pull request merged**
